### PR TITLE
added back support for "from" animationType

### PR DESCRIPTION
**Pull request by CharlieOxendine**

### CODE REVIEW

**Comment by marcosgriselli** [comment]
Thanks @CharlieOxendine. Was planning to add this property back. Will merge it later today/tomorrow.

**Comment by marcosgriselli** [comment]
@CharlieOxendine there's an unexpected file name change included in the PR that causes problems:

Screen Shot 2021-02-20 at 09 56 58
 If you try compiling your fork you'll run into this error message: 
 ```
 error: Build input file cannot be found: '/Users/user/path/ViewAnimator-master/Sources/Models/AnimationType.swift' (in target 'ViewAnimator' from project 'ViewAnimator')
 ```

**Comment by CharlieOxendine** [comment]
Just changed the file name back. Let me know if that works! Thanks!

**Comment by marcosgriselli** [comment]
@CharlieOxendine the `Directions.swift` file is missing from the Xcode project so the library is failing to compile. This is a screenshot from your fork: 

Screen Shot 2021-02-22 at 12 47 44

**Comment by CharlieOxendine** [comment]
Sorry for the late reply, but the file name is Direction.swift, but it does exist and runs fine for me. Would the file name "Directions" missing be what's causing the issue? I just pushed a version with the file name changed to my fork

**Comment by CharlieOxendine** [comment]
Screen Shot 2021-06-12 at 1 08 58 PM

**Comment by marcosgriselli** [comment]
@CharlieOxendine I just pulled your fork. The file is not added to Xcode even though it exists the system folder: 
image

You should be able to replicate this by cloning your fork again. Xcode can get files to a weird state when renaming + adding/removing them so it might be using some cache version on your local machine but it does not work for others or for CI. Dragging and dropping `Directions.swift` to the Models folder in the Xcode navigator should fix the issue. If you are currently seeing `Directions.swift` in the Models folder on Xcode simply delete it (Remove References) and drag-drop it again.

**Comment by CharlieOxendine** [comment]
I just cloned my project again but I don't see this error. I tried deleting the Directions.swift file and dragging it back in. Should I try and push with that? Sorry for the trouble

**Comment by marcosgriselli** [comment]
> I just cloned my project again but I don't see this error. I tried deleting the Directions.swift file and dragging it back in. Should I try and push with that? Sorry for the trouble

Yeah, there should be a change in the Xcode project file to commit. 

No worries! I'm down to workout issues with anyone that wants to contribute :)

**Comment by CharlieOxendine** [comment]
The only change to commit is with ".swiftpm"

**Comment by marcosgriselli** [comment]
@CharlieOxendine can you give me push permissions to your fork? I'm not 100% sure what's going on on your side (maybe using the Swift Package project instead of the Xcode one) but I have the line to fix it so we can merge it.

**Comment by CharlieOxendine** [comment]
Yeah, will do👍🏻

**Pull request merged**
