### PR TITLE
Feature: Timing functions

### PR DESCRIPTION
**Pull request by marcosgriselli**
This PR adds support for [Predefined Timing Functions](https://developer.apple.com/documentation/quartzcore/camediatimingfunction/predefined_timing_functions). The library used the UIView animation API with springs which doesn't rely on timing functions. 

To support this I had to remove. the default spring parameters so the method's signature would differ. Since this is a breaking change I also went ahead a replaced the `AnimationType.from(Direction, CGFloat)` case for `AnimationType.vector(Vector)`.

I'll keep this PR open for the weekend in case anybody wants to comment.

### CODE REVIEW

**Comment by iTarek** [comment]
Hi, Please update the readme examples. Also is there any example for using AnimationType.vector
Thank you

**Comment by marcosgriselli** [comment]
Good call @iTarek! I'll update the examples shortly. What you're looking for is: 
`let aniMove = AnimationType.vector((CGVector(dx: 0, dy: self.view.height/2))` 

Both `CollectionViewController.swift` and TableViewController.swift` files have examples using the `.vector` animation you can check those. I'll update the docs shortly.

**Comment by iTarek** [comment]
The AnimationType.vector is so confusing, I have icon on middle of screen and I was able to animate it to go down off screen like that....
let animMove = AnimationType.from(direction: .bottom, offset: self.view.height/2)
loadingViewIcon.animate(animations: [animMove], reversed: true, initialAlpha: 1, finalAlpha: 1, duration: 20.2)

Right now with AnimationType.vector the icon not start from the position it was before but it jumps to the new position and then move back, Is  reversed: true working as it was before?

**Comment by marcosgriselli** [comment]
@iTarek you're right. There's some odd behavior. The example app is working in the same way as before with UITableView and UICollectionView but I individual views have problems. 

I'll send a PR fixing this and adding examples shortly. 

In the meantime I recommend you switch back to the previous release `2.7.0` to avoid any issues and still be able to use the directions as before.

**Comment by iTarek** [comment]
> @iTarek you're right. There's some odd behavior. The example app is working in the same way as before with UITableView and UICollectionView but I individual views have problems.
> 
> I'll send a PR fixing this and adding examples shortly.
> 
> In the meantime I recommend you switch back to the previous release `2.7.0` to avoid any issues and still be able to use the directions as before.

Thank you for the quick response, I will wait for the next update 😊

**Comment by marcosgriselli** [comment]
@iTarek after some review I believe the functionality is working as expected. I agree the API is a bit confusing but I'm testing the example project and running this code: 

```swift
let animation = AnimationType.vector(CGVector(dx: 0, dy: 30))
activityIndicator.animate(animations: [animation], reversed: true, initialAlpha: 1, finalAlpha: 0)
```

will effectively animate the view by moving it from its current position 30 points to the bottom. Can you maybe replicate the issue you're having on a PR or demo project?

**Pull request merged**
