### PR TITLE
#Foundation Replice  with UIKit for bug fix(Unknown type 'CGFLoat')

### PR DESCRIPTION
**Pull request by moosamir68**
#Foundation Replice  with UIKit for bug fix(Unknown type 'CGFLoat') did you min 'CGFloat'

### CODE REVIEW

**Comment by marcosgriselli** [comment]
@moosamir68 where are you seeing the **Unknown type 'CGFLoat'** issue?

**Comment by moosamir68** [comment]
@marcosgriselli AnimationType.swift, Direction.swift, Animation.swift, Utilities.swift, ViewAnimatorConfig.swift

**Comment by marcosgriselli** [comment]
But is it when cloning the repo? or Cocoapods/Carthage? I can't find it.

**Comment by moosamir68** [comment]
@marcosgriselli when add from pod, animate method cant find. Because of this, I copied the files to project and run the project get error

**Pull request merged**
