### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by ApolloZhu**
Fixed warnings in Swift 5 and updated project settings. 

But should utility methods for generating random numbers really be part of the public API (given that [SE-0202](https://github.com/apple/swift-evolution/blob/master/proposals/0202-random-unification.md) introduced unified RNG with Swift 4.2)?

### CODE REVIEW

**Comment by ApolloZhu** [comment]
I don't have access to the build log, but I assume it failed because bitrise is not using Xcode 10.2? Should it be any other reason, please let me know.

**Comment by marcosgriselli** [comment]
> I don't have access to the build log, but I assume it failed because bitrise is not using Xcode 10.2? Should it be any other reason, please let me know.

Right, I just re-launched the build with an updated stack.

**Comment by marcosgriselli** [comment]
```
But should utility methods for generating random numbers really be part of the public API (given that SE-0202 introduced unified RNG with Swift 4.2)?
``` 
We can remove those. I'll add a patch for it after.

**Comment by marcosgriselli** [comment]
Thanks for the PR @ApolloZhu !

**Pull request merged**
